spring.application.name=supply-chain-base-operations
spring.datasource.url=jdbc:postgresql://localhost:5432/supply-chain-easy-db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.mail.username=6206472735rahul@gmail.com
spring.mail.password=ceffelhhjfderwei